Web/Models/Home/DashboardVM.cs
namespace Web.Models.Home
{
	public class DashboardVM
	{
		public int TotalUsers { get; set; }

		public int TotalAdmins { get; set; }

		public int TotalStaffs { get; set; }

		public int TotalPatients { get; set; }

		public int TotalDiseases { get; set; }

		public int TotalActiveUsers { get; set; }

		public int TotalActivePatients { get; set; }

		public int TotalDischargedPatients { get; set; }
	}
}

Web/Controllers/DiseaseController.cs
using AutoMapper;
using DbLayer.Helpers;
using DbLayer.Models.Patient;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces.Patient;
using ServiceLayer.Interfaces;
using Web.Helper;
using Web.Models.Disease;
using ServiceLayer.Interfaces.Settings;

namespace Web.Controllers
{
	public class DiseaseController : BaseController
	{
		private readonly IDiseaseService _disease;
		private readonly IPatientsService _patient;
		private readonly IStaffService _staff;
		private readonly IDiseaseTypeService _diseaseType;
		private readonly IMapper _mapper;

		public DiseaseController(
			IDiseaseService disease,
			IPatientsService patient,
			IStaffService staff,
			IDiseaseTypeService diseaseType,
			IMapper mapper)
		{
			_disease = disease;
			_patient = patient;
			_staff = staff;
			_diseaseType = diseaseType;
			_mapper  = mapper;
		}

		/// <summary>
		/// Disease index page
		/// </summary>
		/// <returns></returns>
		public IActionResult Index()
		{
			return View();
		}

		/// <summary>
		/// Disease details page by disease id
		/// </summary>
		/// <returns></returns>
		public IActionResult Details(int id)
		{
			return View(new DiseaseMainVM(id));
		}

		/// <summary>
		/// Load list of diseases
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> DiseaseList()
		{
			var diseases = await _disease.ListAsync();
			var model = _mapper.Map<List<DiseaseVM>>(diseases);

			return PartialView("Containers/_DiseaseList", model);
		}

		/// <summary>
		/// Load details of disease by id
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> DiseaseDetails(int id)
		{
			var disease = await _disease.DetailsAsync(id);
			var model   = _mapper.Map<DiseaseVM>(disease);

			return PartialView("Containers/_DiseaseDetails", model);
		}

		/// <summary>
		/// Load Add of edit modal for disease based on id passed
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> AddEdit(int id)
		{
			var model = new DiseaseDetailsVM()
			{
				PatientList     = await _patient.PatientSelectList(),
				StaffList       = await _staff.StaffSelectList(),
				DiseaseTypeList = await _diseaseType.DiseaseTypeSelectList()
			};

			if (id.IsZeroOrLess())
				return PartialView("Popups/_AddEditDisease", model);

			var disease = await _disease.DetailsAsync(id);
			model.Details = _mapper.Map<DiseaseVM>(disease);


			return PartialView("Popups/_AddEditDisease", model);
		}

		/// <summary>
		/// Add or edit disease
		/// </summary>
		/// <param name="model"></param>
		/// <returns></returns>
		[HttpPost]
		public async Task<IActionResult> AddEdit(DiseaseDetailsVM model)
		{
			if (!TryValidateModel(model.Details))
				return JsonError("Fields are not valid");

			var disease = _mapper.Map<Disease>(model.Details);
			var isAdd   = model.Details.DiseaseId.IsNullOrZero();

			var result = string.Empty;

			if (isAdd)
				result = await _disease.AddAsync(disease, UserHelper.GetCurrentUser());
			else
				result = await _disease.UpdateAsync(disease, UserHelper.GetCurrentUser());

			if (!string.IsNullOrEmpty(result))
				return JsonError(result);

			return JsonSuccess($"Disease {(isAdd ? "added" : "updated")} successfully.");
		}
	}
}

Web/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using System.Diagnostics;
using Web.Helper;
using Web.Models;
using Web.Models.Home;

namespace Web.Controllers
{
    public class HomeController : BaseController
	{
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeService _home;
		private readonly IMapper _mapper;

		public HomeController(
            ILogger<HomeController> logger, 
            IHomeService home,
			IMapper mapper)
        {
            _logger = logger;
            _home   = home;
            _mapper = mapper;
        }

        /// <summary>
        /// Home index page dashboard
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var result = await _home.DetailsAsync(UserHelper.GetCurrentUser());
            var model  = _mapper.Map<DashboardVM>(result);

			return View(model);
        }

		/// <summary>
		/// Current user profile
		/// </summary>
		/// <returns></returns>
		public IActionResult Profile()
		{
			return View();
		}

		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/StaffController.cs
using AuthLayer.Interfaces;
using AutoMapper;
using DbLayer.Helpers;
using DbLayer.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using Web.Helper;
using Web.Models.Staff;

namespace Web.Controllers
{
	public class StaffController : BaseController
	{
		private readonly IStaffService _staff;
		private readonly IUserService _user;
		private readonly IMapper _mapper;

		public StaffController(
			IStaffService staff,
			IUserService user,
			IMapper mapper)
		{
			_user   = user;
			_staff  = staff;
			_mapper = mapper;
		}

		/// <summary>
		/// Staff index page
		/// </summary>
		/// <returns></returns>
		public IActionResult Index()
		{
			return View();
		}

		/// <summary>
		/// Staff details page by Id
		/// </summary>
		/// <returns></returns>
		public IActionResult Details(string id)
		{
			return View(new StaffMainDetails(id));
		}

		/// <summary>
		/// Load list of staffs
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> StaffList()
		{
			var staffs = await _staff.ListAsync();
			var model = _mapper.Map<List<StaffVM>>(staffs);

			return PartialView("Containers/_StaffList", model);
		}

		/// <summary>
		/// Load details of staff by id
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> StaffDetails(string id)
		{
			var staff = await _staff.DetailsAsync(id);
			var model = _mapper.Map<StaffVM>(staff);

			return PartialView("Containers/_StaffDetails", model);
		}

		/// <summary>
		/// Load Add of edit modal for staff based on id passed
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> AddEdit(string id)
		{
			var model = new StaffDetailsVM()
			{
				UsersList = await _user.UserBasedOnRoleList(UserRole.Staff),
			};

			if (string.IsNullOrEmpty(id))
				return PartialView("Popups/_AddEditStaff", model);

			var staff = await _staff.DetailsAsync(id);
			model.Details = _mapper.Map<StaffVM>(staff);


			return PartialView("Popups/_AddEditStaff", model);
		}

		/// <summary>
		/// Add or edit staff
		/// </summary>
		/// <param name="model"></param>
		/// <returns></returns>
		[HttpPost]
		public async Task<IActionResult> AddEdit(StaffDetailsVM model)
		{
			if (!TryValidateModel(model.Details))
				return JsonError("Fields are not valid");

			var staff = _mapper.Map<Staff>(model.Details);
			var isAdd = model.Details.StaffId.IsNullOrZero();

			var result = string.Empty;

			if (isAdd)
				result = await _staff.AddAsync(staff, UserHelper.GetCurrentUser());
			else
				result = await _staff.UpdateAsync(staff, UserHelper.GetCurrentUser());

			if (!string.IsNullOrEmpty(result))
				return JsonError(result);

			return JsonSuccess($"Staff {(isAdd ? "added" : "updated")} successfully.");
		}
	}
}

Web/Controllers/UserController.cs
using AuthLayer.Interfaces;
using AuthLayer.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using Web.Models.Account;
using Web.Models.User;

namespace Web.Controllers
{
    public class UserController : BaseController
	{
		private readonly IUserService _user;
		private readonly IRoleService _role;
		private readonly IMapper _mapper;

		public UserController(
			IUserService user,
			IRoleService role,
			IMapper mapper)
        {
			_user    = user;
			_role    = role;
			_mapper  = mapper;
        }

        /// <summary>
        /// Application users index page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
		{
			return View();
		}		

		/// <summary>
		/// Application users details page
		/// </summary>
		/// <returns></returns>
		public IActionResult Details(string id)
		{
			return View(new UserDetailsVM(id));
		}

		/// <summary>
		/// Load list of users approved or not
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> List(bool isApproved)
		{
			var users = await _user.ListAsync(isApproved);
			var model = _mapper.Map<List<UserVM>>(users);

			return PartialView("Containers/_UsersList", model);
		}

		/// <summary>
		/// Load details of user by id
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> UserDetails(string id)
		{
			var users = await _user.DetailsAsync(id);
			var model = _mapper.Map<UserVM>(users);

			return PartialView("Containers/_UserDetails", model);
		}

		/// <summary>
		/// Load mini details of user by id
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> UserDetailsMini(string id)
		{
			var users = await _user.DetailsAsync(id);
			var model = _mapper.Map<UserVM>(users);

			return PartialView("Containers/_UserDetailsMini", model);
		}

		/// <summary>
		/// Load Add of edit modal based on id passed
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<PartialViewResult> AddEdit(string id)
		{
			if (string.IsNullOrEmpty(id))
				return PartialView("Popups/_AddEditUser");

			var user  = await _user.DetailsAsync(id);
			var model = _mapper.Map<UserVM>(user);

			return PartialView("Popups/_AddEditUser", model);
		}

		/// <summary>
		/// Add or update users to the system
		/// </summary>
		/// <param name="model"></param>
		/// <returns></returns>
		[HttpPost]
		public async Task<IActionResult> AddEdit(UserVM model)
		{
			if (!ModelState.IsValid)
				return JsonError("Fields are not valid");

			var user   = _mapper.Map<AppUser>(model);
			var result = new AuthResults();
			var isAdd  = string.IsNullOrEmpty(model.Id);

			if (isAdd)
				result = await _user.AddAsync(user);
			else
				result = await _user.UpdateAsync(user);

			if (!result.Success)
			{
				foreach (var error in result.Errors)
				{
					ModelState.AddModelError(string.Empty, error);
				}

				return JsonError("Submit user unsuccessful.");
			}
			return JsonSuccess($"User {(isAdd ? "added" : "updated")} successfully.");
		}

        /// <summary>
        /// Load Add of edit modal based on id passed
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> ApproveUnApprove(string id, bool isApprove = false)
        {
			if (string.IsNullOrEmpty(id))
				return JsonError("User id not found.");

            var model = new UserDetailsVM()
			{
				UserId    = id,
				IsApprove = isApprove
			};

            return PartialView("Popups/_ApproveUser", model);
        }

		/// <summary>
		/// Approve or un approve user by id
		/// </summary>
		/// <param name="model"></param>
		/// <returns></returns>
		[HttpPost]
		public async Task<IActionResult> ApproveUnApprove(UserDetailsVM model)
		{
            var result = await _user.ApproveUserAsync(model.UserId, model.IsApprove);

            if (!result.Success)
                return JsonError("User status change unsuccessful.");

            return JsonSuccess($"User {(model.IsApprove ? "approved" : "un-approved")} successfully.");
        }

		/// <summary>
		/// Load list of user roles for the user id givem
		/// </summary>
		/// <returns></returns>
		public async Task<PartialViewResult> UserRoleList(string id)
		{
			var roles   = await _user.UserRolesListAsync(id);
			var list = _mapper.Map<List<UsersVsRolesVM>>(roles);

			var model = new UserRolesDetailsVM()
			{
				List = list
            };

			model.Details.UserId = id;

            return PartialView("Containers/_UserRolesList", model);
		}

		/// <summary>
		/// Load assign role modal based on id passed
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> AssignRole(string id)
		{
			if (string.IsNullOrEmpty(id))
				return JsonError("User id not found.");

			var user = await _user.DetailsAsync(id);

			if (user == null)
				return JsonError("User not found.");

			var roles = await _role.RolesSelectList();

			var model = new UserRolesDetailsVM()
			{
				RolesList = roles
			};

			model.Details.UserId = user.Id;

			return PartialView("Popups/_AssignRole", model);
		}

        /// <summary>
        /// Assign a role to the user
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AssignRole(UserRolesDetailsVM model)
        {
            if (!TryValidateModel(model.Details))
                return JsonError("Fields are not valid");

            var userRole = _mapper.Map<ViewUsersVsRoles>(model.Details);
            var result   = await _role.AssignRoleAsync(userRole);

            if (!result.success)
            {
                foreach (var error in result.errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }

                return JsonError(result.errors[0]);
            }
            return JsonSuccess($"Role assigned to the user successfully.");
        }

		/// <summary>
		/// Load un - assign role modal based on ids passed
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> UnAssignRole(string id, string userId)
		{
			if (string.IsNullOrEmpty(id))
				return JsonError("Role id not found.");

			if (string.IsNullOrEmpty(userId))
				return JsonError("User id not found.");

			var model = new UserRolesDetailsVM();

			model.Details.RoleId = id;
			model.Details.UserId = userId;

			return PartialView("Popups/_UnAssignRole", model);
		}

        /// <summary>
        /// Assign a role to the user
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UnAssignRole(UserRolesDetailsVM model)
        {
            if (!TryValidateModel(model.Details))
                return JsonError("Fields are not valid");

            var userRole = _mapper.Map<ViewUsersVsRoles>(model.Details);
            var result   = await _role.AssignRoleAsync(userRole, true);

            if (!result.success)
            {
                foreach (var error in result.errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }

                return JsonError(result.errors[0]);
            }
            return JsonSuccess($"Role un-assigned to the user successfully.");
        }

		/// <summary>
		/// Upload profile picture and return path
		/// </summary>
		/// <param name="file"></param>
		/// <param name="id"></param>
		/// <returns></returns>
		[HttpPost]
		public async Task<IActionResult> UploadProfilePic(IFormFile file, string id)
		{
			if (file == null || file.Length == 0)
				return JsonError("Uploaded file not found.");

			// Define the target directory and file name
			var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/uploads");
			Directory.CreateDirectory(uploadsFolder);

			var uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
			var filePath       = Path.Combine(uploadsFolder, uniqueFileName);

			// Save the file locally
			using (var fileStream = new FileStream(filePath, FileMode.Create))
			{
				await file.CopyToAsync(fileStream);
			}

			// Save the path to the database
			var imagePath = $"/images/uploads/{uniqueFileName}";

			// appload to the database
			var result = await _user.UpdateProfilePic(id, imagePath);

			if (!result.Success)
				return JsonError(result.Errors[0]);

			return JsonSuccess(result.Message);
		}
    }
}

Web/Views/Home/Index.cshtml
@using Web.Helper
@using Web.Models.Home

@model DashboardVM

@{
	ViewBag.Title = "Home";
	var currentUser = UserHelper.GetCurrentUser();
	var role = UserHelper.GetCurrentRole();
}

<div class="container-fluid p-0">

	<div class="row mb-2 mb-xl-3">
		<div class="col-auto d-none d-sm-block">
			<h3>Dashboard</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-6 col-xxl-7 p-2">
			<div class="card flex-fill h-100 w-100">
				<div class="card-header">					
					<h5 class="card-title mb-0">Welcome Card</h5>
				</div>
				<div class="card-body pt-2 pb-3">
					<div class="chart chart-sm">
						<div>
							<h1 class="font-big"><b>Welcome,</b> @currentUser.FullName</h1>
							<h4 class="text-muted">Here you can see overview of the app and access via quick links.</h4>
						</div>
						<div class="row">
							<div class="col-xl-6 d-flex align-items-center justify-content-center">
								<div class="card w-75 m-0">
									<div class="card-body">
										<div class="row">
											<div class="col mt-0">
												<h5 class="card-title">Total active users</h5>
											</div>
											<div class="col-auto">
												<div class="stat text-primary">
													<i class="align-middle" data-feather="user-check"></i>
												</div>
											</div>
										</div>
										<h1 class="mt-1 mb-3">@Model.TotalActiveUsers</h1>
									</div>
								</div>
							</div>
							<div class="col-xl-6 d-flex justify-content-center justify-content-xl-end">
								<img class="img-fluid col-xl-12 col-xxl-10" src="~/img/general/welcome-card-pic.png" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xl-6 col-xxl-5">
			<div class="row h-100">
				<div class="col-sm-6 p-2">
					<div class="card h-100">
						<div class="card-body">
							<div class="row">
								<div class="col mt-0">
									<h5 class="card-title">Users</h5>
								</div>

								<div class="col-auto">
									<div class="stat text-primary">
										<i class="align-middle" data-feather="users"></i>
									</div>
								</div>
							</div>
							<h1 class="mt-1 mb-3">@Model.TotalUsers</h1>
							<div class="mb-0">
								@if (role.IsAdmin)
								{
									<a asp-controller="User" asp-action="Index">
										<span class="badge badge-primary-light"> <i class="mdi mdi-arrow-bottom-right"></i> View more </span>
									</a>
								}					
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6 p-2">
					<div class="card h-100">
						<div class="card-body">
							<div class="row">
								<div class="col mt-0">
									<h5 class="card-title">Staffs</h5>
								</div>

								<div class="col-auto">
									<div class="stat text-primary">
										<i class="align-middle" data-feather="user-plus"></i>
									</div>
								</div>
							</div>
							<h1 class="mt-1 mb-3">@Model.TotalStaffs</h1>
							<div class="mb-0">
								@if (role.IsAdmin)
								{
									<a asp-controller="Staff" asp-action="Index">
										<span class="badge badge-success-light"> <i class="mdi mdi-arrow-bottom-right"></i> View more </span>
									</a>
								}
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6 p-2">
					<div class="card h-100">
						<div class="card-body">
							<div class="row">
								<div class="col mt-0">
									<h5 class="card-title">Patients</h5>
								</div>

								<div class="col-auto">
									<div class="stat text-primary">
										<i class="align-middle" data-feather="heart"></i>
									</div>
								</div>
							</div>
							<h1 class="mt-1 mb-3">@Model.TotalPatients</h1>
							<div class="mb-0">
								@if (role.IsAdmin || role.IsStaff)
								{
									<a asp-controller="Patient" asp-action="Index">
										<span class="badge badge-success-light"> <i class="mdi mdi-arrow-bottom-right"></i> View more </span>
									</a>
								}
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6 p-2">
					<div class="card h-100">
						<div class="card-body">
							<div class="row">
								<div class="col mt-0">
									<h5 class="card-title">Diseases</h5>
								</div>

								<div class="col-auto">
									<div class="stat text-primary">
										<i class="align-middle" data-feather="alert-triangle"></i>
									</div>
								</div>
							</div>
							<h1 class="mt-1 mb-3">@Model.TotalDiseases</h1>
							<div class="mb-0">
								@if (role.IsAdmin || role.IsStaff)
								{
									<a asp-controller="Disease" asp-action="Index">
										<span class="badge badge-danger-light"> <i class="mdi mdi-arrow-bottom-right"></i> View more </span>
									</a>
								}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>

	<div class="row">
		<div class="col-12 col-md-6 col-xxl-3 p-2 d-flex order-1 order-xxl-3">
			<div class="card flex-fill h-100 w-100">
				<div class="card-header">
					<h5 class="card-title mb-0">Patients</h5>
				</div>
				<div class="card-body d-flex">
					<div class="align-self-center w-100">
						<div class="py-3">
							<div class="chart chart-xs">
								<canvas id="chartjs-dashboard-pie"></canvas>
							</div>
						</div>

						<table class="table mb-0">
							<tbody>
								<tr>
									<td><i class="fas fa-circle text-light-primary fa-fw"></i> Active</td>
									<td class="text-end">@Model.TotalActivePatients</td>
								</tr>
								<tr>
									<td><i class="fas fa-circle text-light-danger fa-fw"></i> Discharged</td>
									<td class="text-end">@Model.TotalDischargedPatients</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-12 col-xxl-6 p-2 d-flex order-3 order-xxl-2">
			<div class="card flex-fill h-100 w-100">
				<div class="card-header">
					<h5 class="card-title mb-0">Application Users</h5>
				</div>
				<div class="card-body d-flex">
					<div class="align-self-center w-100">
						<div class="py-3">
							<div class="chart chart-xs">
								<canvas id="chartjs-dashboard-bar"></canvas>
							</div>
						</div>

						<table class="table mb-0">
							<tbody>
								<tr>
									<td><i class="fas fa-circle text-light-primary fa-fw"></i> Active Users</td>
									<td class="text-end">@Model.TotalActiveUsers</td>
								</tr>
								<tr>
									<td><i class="fas fa-circle text-light-success fa-fw"></i> Admins</td>
									<td class="text-end">@Model.TotalAdmins</td>
								</tr>
								<tr>
									<td><i class="fas fa-circle text-light-warning fa-fw"></i> Staffs</td>
									<td class="text-end">@Model.TotalStaffs</td>
								</tr>
								<tr>
									<td><i class="fas fa-circle text-light-danger fa-fw"></i> Patients</td>
									<td class="text-end">@Model.TotalPatients</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-6 col-xxl-3 p-2 d-flex order-2 order-xxl-1">
			<div class="card flex-fill h-100">
				<div class="card-header">
					<h5 class="card-title mb-0">Calendar</h5>
				</div>
				<div class="card-body d-flex">
					<div class="align-self-center w-100">
						<div class="chart">
							<div id="datetimepicker-dashboard"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>

@section scripts {

	@*----- Calender render -----*@
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var date = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000);
			var defaultDate = date.getUTCFullYear() + "-" + (date.getUTCMonth() + 1) + "-" + date.getUTCDate();
			document.getElementById("datetimepicker-dashboard").flatpickr({
				inline: true,
				prevArrow: "<span class=\"fas fa-chevron-left\" title=\"Previous month\"></span>",
				nextArrow: "<span class=\"fas fa-chevron-right\" title=\"Next month\"></span>",
				defaultDate: defaultDate
			});
		});
	</script>


	@*---- Chart render ----*@
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			// Doughnut chart
			new Chart(document.getElementById("chartjs-dashboard-pie"), {
				type: "doughnut",
				data: {
					labels: ["Active", "Discharged"],
					datasets: [{
						data: [
							@Model.TotalActivePatients,
							@Model.TotalDischargedPatients
						],
						backgroundColor: [
							"#cfe2ff",
							"#f8d7da"
						],
						borderWidth: 5,
						borderColor: "#fff"
					}]
				},
				options: {
					responsive: true,
					maintainAspectRatio: false,
					plugins: {
						legend: {
							display: false 
						}
					},
					cutoutPercentage: 70
				}
			});

			// Bar Chart
			new Chart(document.getElementById("chartjs-dashboard-bar"), {
				type: "bar",
				data: {
					labels: ["Active Users", "Admins", "Staffs", "Patients"],
					datasets: [{
						data: [
							@Model.TotalActiveUsers,
							@Model.TotalAdmins,
							@Model.TotalStaffs,
							@Model.TotalPatients
						],
						backgroundColor: [
							"#cfe2ff",
							"#d1e7dd",
							"#fff3cd",
							"#f8d7da"
						],
						borderWidth: 1,
						borderColor: "#fff"
					}]
				},
				options: {
					responsive: true,
					maintainAspectRatio: false,
					plugins: {
						legend: {
							display: false 
						},
						tooltip: {
							enabled: true
						}
					}
				}
			});
		});		
	</script>
}

Web/Views/Home/Profile.cshtml
@using Web.Helper

@{
	ViewBag.Title = "Profile";
	var currentUser = UserHelper.GetCurrentUser();
}

<div class="container-fluid p-0">

	<div class="mb-3">
		<h1 class="h3 d-inline align-middle">Profile</h1>
	</div>

	<div class="row">
		<div class="col-12">
			<div class="card main-frame-card">
				<div class="card-header d-flex justify-content-between align-content-between align-items-center flex-wrap">
					<div>
						<h5 class="card-title">Profile details</h5>
						<h6 class="card-subtitle text-muted">
							Here you can manage profile.
						</h6>
					</div>
				</div>
				<div class="card-body" id="@ContainerId.UsersList">
				</div>
			</div>
		</div>
	</div>
</div>

@section scripts {

	<script>
		(function(){

			// Load users detail
			var LoadProfileDetails = function () {
				Controls.RelaodContainer('@Url.Action("UserDetails", "User", new { id = currentUser.UserId })', '@ContainerId.UsersList');
			}

			// Call profile details
			LoadProfileDetails();

			// Open popup modal for edit a user details
			$(document).on('click', '#@ButtonId.UserEdit', function () {
				var id  = $(this).data("id");
				var url = `@Url.Action("AddEdit", "user")?id=${id}`;

				Controls.OpenPopUpModal(url, "@UniqueIdentifier.MainModelId", "User Approval");
			});

			/**
			* Submit the form via ajax and close the modal
			*/
			$(document).on('click', '.@ButtonClass.MainModalSubmit', function () {
				var form = $(this).closest('.modal').find('.modal-body form');

				Controls.RelaodContainerOnModalPost("@UniqueIdentifier.MainModelId", form, '@ContainerId.UsersList', LoadProfileDetails);
			});
		})();
	</script>
}